#ifndef HLSL_SHARED_DEFINES
#define HLSL_SHARED_DEFINES

#define A_BOUNDINGBOXES_XTHREADS 1024
#define A_BOUNDINGBOXES_YTHREADS 1
#define A_BOUNDINGBOXES_ZTHREADS 1

#define B_SCENEBOUNDINGBOX_XTHREADS 1024
#define B_SCENEBOUNDINGBOX_YTHREADS 1
#define B_SCENEBOUNDINGBOX_ZTHREADS 1

#define C_FILLCOUNTERTREES_XTHREADS 1024
#define C_FILLCOUNTERTREES_YTHREADS 1
#define C_FILLCOUNTERTREES_ZTHREADS 1

#define D_GLOBALCOUNTERTREE_XTHREADS 1024
#define D_GLOBALCOUNTERTREE_YTHREADS 1
#define D_GLOBALCOUNTERTREE_ZTHREADS 1

//#define TREESIZE_7 2396745

#define SUBDIVS 7


#endif