#ifndef HLSL_SHARED_DEFINES
#define HLSL_SHARED_DEFINES

// beinhaltet Gruppengrößen von verschiedenen Compute Shadern

#define LINEAR_XTHREADS 1024
#define LINEAR_YTHREADS 1
#define LINEAR_ZTHREADS 1

#define _5_FILLTYPETREE_XTHREADS 8
#define _5_FILLTYPETREE_YTHREADS 8
#define _5_FILLTYPETREE_ZTHREADS 8

#define _6_FILLLEAFINDEXTREE_XTHREADS 8
#define _6_FILLLEAFINDEXTREE_YTHREADS 8
#define _6_FILLLEAFINDEXTREE_ZTHREADS 8

#define SUBDIVS 7

#endif