#ifndef HLSL_SHARED_DEFINES
#define HLSL_SHARED_DEFINES

#define A_BOUNDINGBOXES_XTHREADS 1024
#define A_BOUNDINGBOXES_YTHREADS 1
#define A_BOUNDINGBOXES_ZTHREADS 1

#define B_SCENEBOUNDINGBOX_XTHREADS 1024
#define B_SCENEBOUNDINGBOX_YTHREADS 1
#define B_SCENEBOUNDINGBOX_ZTHREADS 1

//#define TREESIZE_7 2396745

#define LEVELS 7


#endif